version: "3.7"
services:
  app:
    build:
      args:
        user: blog
        uid: 1000
      dockerfile: Dockerfile
    image: blog
    container_name: blog-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./laravel-test/:/var/www
    networks:
      - blog

  db:
    image: postgres:latest
    container_name: blog-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: "blog"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - blog

  nginx:
    image: nginx:alpine
    container_name: blog-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./laravel-test/:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - blog

networks:
    blog:
        driver: bridge
