version: "3.7"
services:
  app:
    build:
      args:
        user: blog
        uid: 1000
      dockerfile: Dockerfile
    image: blog
    container_name: blog-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./laravel-test/:/var/www
    networks:
      - blog

  db:
    image: mysql:latest
    platform: linux/x86_64
    container_name: blog-db
    restart: unless-stopped
    environment:
        MYSQL_DATABASE: blog
        MYSQL_ROOT_PASSWORD: root
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    ports:
        - "3306:3306"
    networks:
      - blog

  nginx:
    image: nginx:alpine
    container_name: blog-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./laravel-test/:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - blog

networks:
    blog:
        driver: bridge
